list.txt:	list1.txt list2.txt list3.txt list4.txt list5.txt list6.txt list7.txt list8.txt list9.txt list10.txt list11.txt 
	cp list1.txt list.txt ; cat list2.txt >> list.txt ; cat list3.txt >> list.txt ; cat list4.txt >> list.txt ; cat list5.txt >> list.txt ; cat list6.txt >> list.txt ; cat list7.txt >> list.txt ; cat list8.txt >> list.txt ; cat list9.txt >> list.txt ; cat list10.txt >> list.txt ; cat list11.txt >> list.txt ;

list1.txt:
	premier 2 11 > list1.txt
	
list2.txt:
	premier 2 11 > list2.txt

list3.txt:
	premier 2 11 > list3.txt

list4.txt:
	premier 2 11 > list4.txt

list5.txt:
	premier 2 11 > list5.txt

list6.txt:
	premier 2 11 > list6.txt

list7.txt:
	premier 2 11 > list7.txt

list8.txt:
	premier 2 11 > list8.txt

list9.txt:
	premier 2 11 > list9.txt

list10.txt:
	premier 2 11 > list10.txt

list11.txt:
	premier 2 11 > list11.txt

